name: Linting

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install lint dependencies
        run: |
          pip install wheel setuptools
          pip install black==22.3.0 isort==5.10.1 flake8==4.0.1

      - name: Lint the code
        run: sh shell/lint.sh
